### ISSUE TITLE
建议历史账单的实体ID使用固定名便于首页展示

### ISSUE THREAD

**Issue by whatagoodboy** [WeiYang1982/bj_water#1]
作者您好！
集成中的sensor.xxxxx_2023_09_01_fee使用日期作为名字，会随着时间推移不断新增，当需要添加到首页展示时需要关联实体ID，因为实体ID一直在变化无法固定展示，且无法在同一个实体中跟踪变化情况。
建议针对最新账单使用sensor.xxxxx_biil_0_fee，上期账单使用sensor.xxxxx_biil_1_fee，上上期sensor.xxxxx_biil_2_fee，以此类推作为实体ID，同时实体名称仍可以使用日期命名为20230901_Fee，从而即不影响账期阅读体验，又能固定展示在首页，还可以使用sensor.xxxxx_biil_0_fee的历史记录功能方便查阅每个账期的变化情况。希望作者能考虑优化，谢谢！

**Comment by WeiYang1982** [comment]
@whatagoodboy  我大概明白您的意思了，但是何不用template去匹配呢，类似
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - entity_id: sensor.051351243_*_fee
  exclude: []
这样可否呢？

**Comment by WeiYang1982** [comment]
done
